--CREATING THE DATABASE
CREATE DATABASE Estate

--USING THE DATABASE
USE Estate

--CREATING THE LANDLORD TABLE
CREATE TABLE LANDLORD
(
--OWNER
	LAND_ID INT IDENTITY(1,1) PRIMARY KEY,
	LANDLORD_NAME VARCHAR (200),
	LANDLORD_OCCUPATION VARCHAR(200),
	LANDLORD_SEX VARCHAR(2),
	LANDLORD_DATE_OF_BIRTH DATE,
	LANDLORD_PHONE_NUMBER VARCHAR(15),
--SPOUSE
	SPOUSE_NAME VARCHAR(200) NULL,
	SPOUSE_OCCUPATION VARCHAR(200) NULL,
	SPOUSE_DATE_OF_BIRTH DATE NULL,
	SPOUSE_PHONE_NUMBER VARCHAR(15) NULL,
--DATE OF ADDING RECORD
	CAPTURE_DATE DATE
)

--CREATING THE TENANTS TABLE
CREATE TABLE TENANTS
(
	TENANT_ID INT IDENTITY(1,1)PRIMARY KEY,
	--BUILDING ID IS A FOREIGN KEY FROM BUILDING TABLE
	BUILDING_ID INT FOREIGN KEY REFERENCES BUILDING(BUILD_ID),
	TENANT_NAME VARCHAR(200),
	TENANT_PHONE_NUMBER VARCHAR(15),
	TENANT_OCCUPATION VARCHAR(200),
	TENANCY_TYPE VARCHAR(200),
	--GETTING THE STREET OF THE TENANT
	--STREET VARCHAR(200),
	--GETTING WHEN THE TENANT WAS ADDED TO THE DATABASE
	CAPTURE_DATE DATE
)

--CREATING THE BUILDING TABLE
CREATE TABLE BUILDING
(
	BUILD_ID INT IDENTITY(1,1) PRIMARY KEY,

	--FOREIGN KEY FOR LANDLORD 
	LANDLORD_ID INT FOREIGN KEY REFERENCES LANDLORD(LAND_ID),
	--HOUSE INFORMATION
	STREET_NAME VARCHAR(100),
	HOUSE_ADDRESS VARCHAR(300)

)



--DELETING TABLES
DROP TABLE BUILDING
DROP TABLE TENANTS
DROP TABLE LANDLORD


--DELETING THE DATABASE
DROP DATABASE Estate